//
// Created by boku on 25.07.2020.
//

#ifndef NEURALNETWORKS_NEURALNETWORKSCOLLECTION_H
#define NEURALNETWORKS_NEURALNETWORKSCOLLECTION_H


class NeuralNetworksCollection {

};


#endif //NEURALNETWORKS_NEURALNETWORKSCOLLECTION_H
